import { cn } from "@/lib/utils";
import Nav from "./components/navigation/nav";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="px-6 md:px-12 max-width-7xl max-auto">
        <Nav />
        {children}
      </body>
    </html>
  );
}
